---
version: 2
multicolumn: false
web-width: 500
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/164624/articles/195590/master/file/figures/mass/mass.png"
    path: figures/mass/mass.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/164624/articles/195590/master/folder/figures/mass"
